---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: alpha-team
  name: alpha-team

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: alpha-team
  name: alpha-team
  namespace: alpha-team

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: alpha-team
  name: gotk-reconciler
  namespace: alpha-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: User
  name: gotk:alpha-team:reconciler
- kind: ServiceAccount
  name: alpha-team
  namespace: alpha-team
