apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: alpha-team
  namespace: alpha-team
spec:
  interval: 1m
  url: https://github.com/ramiz-lido/flux-alpha-team
  ref:
    branch: alpha-team
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alpha-team
  namespace: alpha-team
spec:
  serviceAccountName: alpha-team
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: alpha-team
  prune: true
